### ISSUE TITLE
Theme Switch from UT

### ISSUE THREAD

**Issue by vincentmorneau** [vincentmorneau/apex-bootstrap4#40]
This applications cannot be converted to a theme using tab-based navigation, as it uses list-based navigation.`

**Comment by marnusv** [comment]
Hi Vincent

Do you have a work around for this issue?

Thanks

**Comment by vincentmorneau** [comment]
I do. For some reason APEX doesn't like the theme number (102), I believe it's a bug. Can you try changing the theme number to something else? Try 600.

FYI I am still waiting for Bootstrap 4 to release a new stable version before upgrading this project. It was still in alpha-2 at the time.
