### ISSUE TITLE
Select lists don't change value visualy

### ISSUE THREAD

**Issue by LudinJozabeth** [vincentmorneau/apex-bootstrap4#46]
Hi!! I love your work!! I'm using your Material Design theme, and have an issue with the select list. If execute a query that fill many items before or after the load page, the select lists don't chage your value visualy. Can you do help me?

**Comment by vincentmorneau** [comment]
You have that issue with the material design theme? If so, please open an issue here: https://github.com/vincentmorneau/material-apex

And let me know if you're on APEX 5.0 or 5.1.
